// Country list (name + ISO-3166 alpha-2 code). Flags render from flagcdn.com.
export const COUNTRIES: { name: string; code: string }[] = [
  { name: "Afghanistan", code: "AF" }, { name: "Albania", code: "AL" }, { name: "Algeria", code: "DZ" },
  { name: "Angola", code: "AO" }, { name: "Argentina", code: "AR" }, { name: "Armenia", code: "AM" },
  { name: "Australia", code: "AU" }, { name: "Austria", code: "AT" }, { name: "Azerbaijan", code: "AZ" },
  { name: "Bahrain", code: "BH" }, { name: "Bangladesh", code: "BD" }, { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" }, { name: "Bolivia", code: "BO" }, { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" }, { name: "Brazil", code: "BR" }, { name: "Bulgaria", code: "BG" },
  { name: "Cambodia", code: "KH" }, { name: "Cameroon", code: "CM" }, { name: "Canada", code: "CA" },
  { name: "Chile", code: "CL" }, { name: "China", code: "CN" }, { name: "Colombia", code: "CO" },
  { name: "Congo", code: "CG" }, { name: "Croatia", code: "HR" }, { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" }, { name: "Czech Republic", code: "CZ" }, { name: "Denmark", code: "DK" },
  { name: "Ecuador", code: "EC" }, { name: "Egypt", code: "EG" }, { name: "Ethiopia", code: "ET" },
  { name: "Finland", code: "FI" }, { name: "France", code: "FR" }, { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" }, { name: "Ghana", code: "GH" }, { name: "Greece", code: "GR" },
  { name: "Guatemala", code: "GT" }, { name: "Hong Kong", code: "HK" }, { name: "Hungary", code: "HU" },
  { name: "India", code: "IN" }, { name: "Indonesia", code: "ID" }, { name: "Iran", code: "IR" },
  { name: "Iraq", code: "IQ" }, { name: "Ireland", code: "IE" }, { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" }, { name: "Japan", code: "JP" }, { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" }, { name: "Kenya", code: "KE" }, { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" }, { name: "Lebanon", code: "LB" }, { name: "Libya", code: "LY" },
  { name: "Lithuania", code: "LT" }, { name: "Malaysia", code: "MY" }, { name: "Mexico", code: "MX" },
  { name: "Moldova", code: "MD" }, { name: "Morocco", code: "MA" }, { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" }, { name: "Nepal", code: "NP" }, { name: "Netherlands", code: "NL" },
  { name: "New Zealand", code: "NZ" }, { name: "Nigeria", code: "NG" }, { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" }, { name: "Pakistan", code: "PK" }, { name: "Palestine", code: "PS" },
  { name: "Panama", code: "PA" }, { name: "Peru", code: "PE" }, { name: "Philippines", code: "PH" },
  { name: "Poland", code: "PL" }, { name: "Portugal", code: "PT" }, { name: "Qatar", code: "QA" },
  { name: "Romania", code: "RO" }, { name: "Russia", code: "RU" }, { name: "Rwanda", code: "RW" },
  { name: "Saudi Arabia", code: "SA" }, { name: "Senegal", code: "SN" }, { name: "Serbia", code: "RS" },
  { name: "Singapore", code: "SG" }, { name: "Slovakia", code: "SK" }, { name: "Slovenia", code: "SI" },
  { name: "Somalia", code: "SO" }, { name: "South Africa", code: "ZA" }, { name: "South Korea", code: "KR" },
  { name: "Spain", code: "ES" }, { name: "Sri Lanka", code: "LK" }, { name: "Sudan", code: "SD" },
  { name: "Sweden", code: "SE" }, { name: "Switzerland", code: "CH" }, { name: "Syria", code: "SY" },
  { name: "Taiwan", code: "TW" }, { name: "Tanzania", code: "TZ" }, { name: "Thailand", code: "TH" },
  { name: "Tunisia", code: "TN" }, { name: "Turkey", code: "TR" }, { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" }, { name: "United Arab Emirates", code: "AE" }, { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" }, { name: "Uruguay", code: "UY" }, { name: "Uzbekistan", code: "UZ" },
  { name: "Venezuela", code: "VE" }, { name: "Vietnam", code: "VN" }, { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" }, { name: "Zimbabwe", code: "ZW" },
];

export const flagUrl = (code: string) => `https://flagcdn.com/24x18/${code.toLowerCase()}.png`;
export const codeForCountry = (name?: string | null) => COUNTRIES.find((c) => c.name === name)?.code;
